import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.scss"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Auth Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="https://thumb2.jobinjacdn.com/T2QXLChiDup1oy31uTmhPpNHR7w=/fit-in/128x128/filters:strip_exif():fill(white):quality(100)/https://mstorage2.jobinjacdn.com/other/files/uploads/images/2673d0de-de85-4407-9a07-4837c57e185d/main.jpg"
          type="image/jpg"
          sizes="any"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} layout`}>
        {children}
      </body>
    </html>
  )
}
